module.exports = {
    name: "Convert List to Text",

    description: "Convert the list to text.",

    category: "List",

    inputs: [
        {
            "name": "action",
            "title": "Action",
            "description": "Acceptable Types: Action\n\nDescription: Executes this block.",
            "types": ["action"]
        },
        {
            "name": "list",
            "title": "List",
            "description": "Acceptable Types: List, Unspecified\n\nDescription: The list to convert to text.",
            "types": ["list", "unspecified"]
        },
        {
            "name": "separator",
            "title": "Separator",
            "description": "Acceptable Types: Text, Unspecified\n\nDescription: The separator to separate the values from the list. (OPTIONAL)",
            "types": ["text", "unspecified"]
        }
    ],

    options: [],

    outputs: [
        {
            "name": "action",
            "title": "Action",
            "description": "Type: Action\n\nDescription: Executes blocks.",
            "types": ["action"]
        },
        {
            "name": "text",
            "title": "Text",
            "description": "Type: Text\n\nDescription: The text generated by the list conversion.",
            "types": ["text"]
        }
    ],

    code: function(cache) {
        const list = this.GetInputValue("list", cache);
        const separator = this.GetInputValue("separator", cache);

        this.StoreOutputValue(list.join(separator || "\n"), "text", cache);
        this.RunNextBlock("action", cache);
    }
};